### ISSUE TITLE
Menu items style

### ISSUE THREAD

**Issue by priezz** [KenHky/react-native-menu-button#3]
Thank you for the useful module!

Please add an ability to define styles of menu items, both normal and selected.

**Comment by KenHky** [comment]
See 0.2.0

**Comment by priezz** [comment]
I still can't set the item color as it is `View`. I think, `optionStyle` should be applied to the `Text` element within `View`. Maybe it would be better to have `optionsStyle`, `selectedOptionStyle`, `optionsTextStyle` and `selectedOptionTextStyle` params.

**Comment by KenHky** [comment]
I add optionsTextStyle and selectedOptionTextStyle to the 0.3.0 version,and rename optionSelectedStyle to selectedOptionStyle.

**Comment by priezz** [comment]
Great! That is what I was looking for!

However there is still something for 0.4.0 :) :
- you have added `optionTextStyle`, not `optionsTextStyle`, so please rename somewhere (in the code or in the docs)
- you do not support StyleSheet objects as style values, so it requires to do ugly things like `optionsStyle={ StyleSheet.flatten( styles.menu ) }`

Keep moving!
