### ISSUE TITLE
转屏的时候会有问题啊大佬！

### ISSUE THREAD

**Issue by linonetwo** [KenHky/react-native-menu-button#4]
我用了 react-native-orientation 来转屏，然而不幸的是，转屏之后它就不出现了，可能是 Dimensions 的问题？

因为 Dimensions 并不会在转屏后刷新。

**Comment by linonetwo** [comment]
Regard to  https://github.com/facebook/react-native/issues/25 , Simply use Dimensions is not a good choice when you need to layout absolutely.

**Comment by KenHky** [comment]
这个问题应该是react-native的原生modal在转屏的时候不会触发render，而且原生modal也有一些问题。
[https://github.com/facebook/react-native/issues/7708](https://github.com/facebook/react-native/issues/7708)。再次点击按钮的时候应该能出现吧？
还有你的处理方式有些侵入性太强了，需要传props，我想想有没有其他的处理方式。如果你在用的话，建议先用你自己的版本。

**Comment by linonetwo** [comment]
嗯 我也是赶工期狗急跳墙了，做得比较粗糙，毕竟我这的场景是有的页面是强制横屏的。

再次点击按钮依然是显示不了菜单的，点不进菜单也就无所谓 Modal 了。其原因乃你的实现是用一个有屏幕那么宽的遮罩层作为父元素来得知用户想要关闭菜单，但是转屏之后 Dimentions 不会刷新。所以屏幕的宽度变得超级宽，但是遮罩层的宽度依然是原来那么宽，导致本应显示在屏幕右边的菜单因为遮罩层不够宽而显示不出来。

搞这个横屏也是搞死我了， react-native-orientation 配置起来坑比较多，还要配置 .java 文件，不然我本来是想直接用它获取屏幕状态的。
